import type { College } from "../types";

// Sample dataset so the app is fully functional before you connect real
// college data. Replace with a `colleges` table query once Supabase is wired up
// (see supabase/schema.sql — this shape matches that table exactly).
export const sampleColleges: College[] = [
  {
    id: "state-university",
    name: "State University",
    location: "Austin, TX",
    tuition: 11200,
    housing: 9800,
    meal_plan: 4200,
    books: 1200,
    transportation: 900,
    graduation_rate: 74,
    average_salary: 58000,
    average_debt: 24500,
    logo_color: "#7a1f2b",
  },
  {
    id: "lakeside-college",
    name: "Lakeside College",
    location: "Madison, WI",
    tuition: 34500,
    housing: 12400,
    meal_plan: 5100,
    books: 1300,
    transportation: 700,
    graduation_rate: 88,
    average_salary: 67000,
    average_debt: 31200,
    logo_color: "#a8425a",
  },
  {
    id: "riverton-tech",
    name: "Riverton Institute of Technology",
    location: "Portland, OR",
    tuition: 42800,
    housing: 13600,
    meal_plan: 4800,
    books: 1500,
    transportation: 600,
    graduation_rate: 91,
    average_salary: 84000,
    average_debt: 28800,
    logo_color: "#5c7a4e",
  },
  {
    id: "community-first",
    name: "Community First College",
    location: "Columbus, OH",
    tuition: 4800,
    housing: 7200,
    meal_plan: 3600,
    books: 900,
    transportation: 1100,
    graduation_rate: 62,
    average_salary: 46000,
    average_debt: 9800,
    logo_color: "#b8822f",
  },
  {
    id: "harborview-university",
    name: "Harborview University",
    location: "Boston, MA",
    tuition: 51200,
    housing: 15800,
    meal_plan: 5600,
    books: 1400,
    transportation: 500,
    graduation_rate: 94,
    average_salary: 91000,
    average_debt: 33400,
    logo_color: "#9c3b32",
  },
  {
    id: "prairie-state",
    name: "Prairie State University",
    location: "Lincoln, NE",
    tuition: 15600,
    housing: 8900,
    meal_plan: 4100,
    books: 1100,
    transportation: 850,
    graduation_rate: 71,
    average_salary: 54000,
    average_debt: 21300,
    logo_color: "#7a1f2b",
  },
];
